/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    eclipse
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.xerial:sqlite-jdbc:3.34.0")
    implementation("com.google.code.gson:gson:2.7")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
}

sourceSets {
	main {
		java {
			setSrcDirs(listOf("src"))
		}
	}
}

tasks.test {
    useJUnit()

    maxHeapSize = "1G"
}

group = "com.joojet.biblefetcher"
version = "0.0.1-SNAPSHOT"
description = "Bible Fetcher"

