name: BibleFetcherPlugin
main: com.joojet.plugins.biblefetcher.source.BibleFetcherPlugin
version: 1.3
api-version: 1.13
commands:
  bible:
    description: Generates a written book containing specified sections of the Bible. The <start> and <end> parameters are optional.