/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.yaml:snakeyaml:1.26")
    implementation("org.xerial:sqlite-jdbc:3.34.0")
    implementation("org.mockito:mockito-core:2.21.0")
    implementation("org.powermock:powermock-module-junit4:2.0.2")
    implementation("org.powermock:powermock-api-mockito2:2.0.2")
    testImplementation("org.powermock:powermock-module-testng:2.0.2")
    compileOnly("io.papermc.paper:paper-api:1.17-R0.1-SNAPSHOT")
    compileOnly("org.spigotmc:spigot:1.17.1-R0.1-SNAPSHOT")
}

group = "AGCraftPlugins"
version = "1.8.0"
description = "AGCraftPlugins"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
