name: AGCraftPlugins
main: com.joojet.plugins.agcraft.main.AGCraftPlugin
version: 1.4
api-version: 1.13
commands:
  bible:
    description: Generates a written book containing specified sections of the Bible. The <start> and <end> parameters are optional.
    usage: /bible <translation> <book> <chapter> <start> <end>
  clearBibles:
    description: Removes all command-generated bibles from your inventory.
    usage: /clearBibles
  getCoordinates:
    description: Returns the coordinates of your current location in {X,Y,Z format}. This also returns the coordinates of another player in this server if another player is specified.
    usage: /getCoordinates or /getCoordinates <player>