name: AGCraftPlugins
main: com.joojet.plugins.agcraft.main.AGCraftPlugin
version: 1.7.3
api-version: 1.13
commands:
  bible:
    description: Generates a written book containing specified sections of the Bible. The <start> and <end> parameters are optional.
    usage: /bible <translation> <book> <chapter> <start> <end>
  clearBibles:
    description: Removes all command-generated bibles from your inventory.
    usage: /clearbibles
  getCoordinates:
    description: Returns the coordinates of your current location in {X,Y,Z format}. This also returns the coordinates of another player in this server if another player is specified.
    usage: /getcoordinates or /getCoordinates <player>
  clearJunk:
    description: Removes junk items from your inventory based on a list of classifiers. Listed classifiers are common, stone, natural, brewing, and armor.
    usage: / clearjunk or / clearJunk <list of classifiers>
  autosmelt:
    description: Uses the coal / coal blocks / charcoal in your inventory to automatically smelt gold / iron ores to their respective counterparts
    usage: /autosmelt
  warp:
    description: Warps you to either a designated location or their bed spawn. Use /warp home to teleport to your bed spawn.
    usage: /warp <location name>
  getLocations:
    description: Prints all known location name to your chat as a list
    usage: /getlocations <PUBLIC | PRIVATE>
  removeLocation:
    description: Removes a location from the player's list of implemented locations.
    usage: /removelocation <location name>
  setLocation:
    description: Registers the player's current location as a new location in the database as a specified name
    usage: /setlocation <name of location> <PUBLIC | PRIVATE>
  giverespawnticket:
    description: Admin use only
    usage: /giverespawnticket <username>
  removeoldnetherlocations:
    description: Admin use only. Removes all old nether warps from the database.
    usage: /removeoldnetherlocations

  